session_name: go-sro 
start_directory: ~/workspace/go-sro/
windows:
  - window_name: dev
    panes:
      - shell_command: 
        - nvim .
  - window_name: run db
    panes:
      - shell_command: 
        - docker compose up db
  - window_name: run gateway
    shell_command_before:
      - nix develop
    panes:
      - shell_command: 
        - go run gateway-server/server.go
  - window_name: run agent-server
    shell_command_before:
      - nix develop
    panes:
      - shell_command: 
        - sleep 5
        - go run agent-server/server.go
  - window_name: client
    panes:
      - shell_command: 
        - echo "this is where you can run start-game-client.sh"
