DROP TABLE IF EXISTS `SRO_SHARD`.`MASTERIES`;
CREATE TABLE  `SRO_SHARD`.`MASTERIES` (
  `FK_CHAR` int(11) NOT NULL,
  `ID` int NOT NULL,
  `LEVEL` int NOT NULL,
  KEY `FK_CHAR_idx` (`FK_CHAR`),
  CONSTRAINT `FK_MASTERIES_CHAR` FOREIGN KEY (`FK_CHAR`) REFERENCES `SRO_SHARD`.`CHAR` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- This just inserts the masteries for the debugging character

LOCK TABLES `SRO_SHARD`.`MASTERIES` WRITE;
INSERT INTO `SRO_SHARD`.`MASTERIES` (
  `FK_CHAR`,
  `ID`,
  `LEVEL`
) VALUES (4,257, 5),(4,258, 0),(4,259, 0),(4,273, 5),(4,274, 0),(4,275, 0),(4,276, 0);

UNLOCK TABLES;
