DROP TABLE IF EXISTS `SRO_SHARD`.`SKILLS`;
CREATE TABLE  `SRO_SHARD`.`SKILLS` (
  `FK_CHAR` int(11) NOT NULL,
  `ID` int NOT NULL,
  KEY `FK_CHAR_idx` (`FK_CHAR`),
  CONSTRAINT `FK_SKILLS_CHAR` FOREIGN KEY (`FK_CHAR`) REFERENCES `SRO_SHARD`.`CHAR` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- This just inserts the skills for the debugging character
--
 LOCK TABLES `SRO_SHARD`.`SKILLS` WRITE;
 INSERT INTO `SRO_SHARD`.`SKILLS` (
   `FK_CHAR`,
   `ID`
 ) VALUES (4,3), (4,90);

 UNLOCK TABLES;
