name: Lint Go Code

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'feature/**'
    tags-ignore:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.3'
      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0

          golangci-lint run --out-format github-actions